[package]
name = "mdate-rust"
version = "0.1.0"
authors = ["Sean Dwyer <ewetoo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gong = "1.4.0"
libc = "0.2.60"
libm = "0.1.4"

